### ISSUE TITLE
News Reader in Python. 

### ISSUE THREAD

**Issue by imsushant12** [viralvaghela/hacktoberfest_2021#194]
A script in python that uses API to read top 5 newspaper headlines and its briefings.

**Comment by mrvishalsharma** [comment]
Can i work on this please assing me this task

**Comment by viralvaghela** [comment]
would you like to work on this @imsushant12 ?? 
```C
if (yes)
    assign(@imsushant12 ); 
else
    assign(@mrvishalsharma );
```

**Comment by imsushant12** [comment]
Yes I would love too 

if (yes == true)
    assign(@imsushant12 ); 


😅
