### ISSUE TITLE
Notification Reminder in Python.

### ISSUE THREAD

**Issue by imsushant12** [viralvaghela/hacktoberfest_2021#195]
A script that will create pop-up notification after specified time.

**Comment by mrvishalsharma** [comment]
can i work on this project? please assing me this

**Comment by viralvaghela** [comment]
hi, @imsushant12 would you like to work on this ? or this time do you want to give chance to @mrvishalsharma ? sweat_smile

**Comment by imsushant12** [comment]
> hi, @imsushant12 would you like to work on this ? or this time do you want to give chance to @mrvishalsharma ? sweat_smile

hi @viralvaghela , Please assign @mrvishalsharma  this time :)

**Comment by mrvishalsharma** [comment]
> 
> 
> > hi, @imsushant12 would you like to work on this ? or this time do you want to give chance to @mrvishalsharma ? sweat_smile
> 
> hi @viralvaghela , Please assign @mrvishalsharma this time :)

can i work on this issue?

**Comment by viralvaghela** [comment]
Hi @mrvishalsharma , @imsushant12 is already working on that ,you can try something new !
