### ISSUE TITLE
Project marked EXCLUDED

### ISSUE THREAD

**Issue by saran-surya** [viralvaghela/hacktoberfest_2021#436]
The current repo has been marked EXCLUDED in the hacktober-fest website.

**Comment by antoinebollengier** [comment]
Why this project marked EXCLUDED ??? @viralvaghela

**Comment by viralvaghela** [comment]
Hello @antoinebollengier  @saran-surya @ushmita4 I don't know the exact reason but it might be because of DSA PRs, during starting days of October we accepted many DSA PRs and maybe hackoberfest is considering it as spam

**Comment by SwapnilSoni1999** [comment]
I found that generally, all the repo named 'hacktober' are excluded by their system or with manual evaluation and its right, I have [express-dry](https://github.com/SwapnilSoni1999/express-dry) which is legit repo for hacktoberfest and no reach on that repo, whereas people are making hacktoberfest-xxx repo and pull all reach making hacktoberfest meaningless. Its for improving existing libs/frameworks or creating new one which can be helpful but okay none can handle such big rush/crowd.
